name: Optimize map and deploy

on:
  - push

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: "Install dependencies"
        run: npm install

      - name: "Build scripts"
        run: npm run build

      - name: "Move scripts"
        run: mv dist/* .

      - name: Bash
        if: github.ref == 'refs/heads/master'
        run: |
          ls -al
          git config --global user.email "d.negrier@thecodingmachine.com"
          git config --global user.name "David Négrier"
          git checkout master
          git add .
          git commit -am "Adding files"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: master

      - name: Bash2
        run: |
          ls -al
